backend:
  name: github
  repo: scottsandersdev/nuxt-netlifycms
  branch: master # Branch to update
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "articles" # Used in routes, e.g. /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "content/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. title.md
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Pull Quote", name: "quote", widget: "markdown"}
      - {label: "Body 2", name: "body2", widget: "markdown"}
  - name: "home" # Used in routes, e.g. /admin/collections/blog
    label: "Home Page Sections" # Used in the UI
    folder: "content/home" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. title.md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Section 1", name: "sec1", widget: "markdown"}
      - {label: Careers,name: careers,widget: object,fields: [{label: Departments, name: departments, widget: list, fields: [{label: Heading,name: heading,widget: string},{label: Subheading,name: subheading, widget: text},{label: Positions, name: positions,widget: list,fields: [{label: Position,name: position, widget: string},{label: Link, name: link, widget: string}]}]}]}
  - name: "careers" # Used in routes, e.g. /admin/collections/blog
    label: "Careers" # Used in the UI
    folder: "content/careers" # The path to the folder where the documents are stored
    slug: "{{slug}}" # Filename template i.e. title.md
    fields:
      - {label: "Page Slug", name: "title", widget: "string"}
      - {label: "Title", name: "pageTitle", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Hero Text", name: "heroText", widget: "text"}
      - {label: Careers,name: careers,widget: object,fields: [{label: Departments, name: departments, widget: list, fields: [{label: Heading,name: heading,widget: string},{label: Subheading,name: subheading, widget: text},{label: Positions, name: positions,widget: list,fields: [{label: Position,name: position, widget: string},{label: Link, name: link, widget: string}]}]}]}
